### 파이썬 라이브러리 설치

In [1]:
pip install pykrx

Collecting pykrx
  Downloading pykrx-1.0.22-py3-none-any.whl (70 kB)
Requirement already satisfied: datetime in c:\users\hingu\anaconda3\lib\site-packages (from pykrx) (4.3)
Requirement already satisfied: numpy in c:\users\hingu\anaconda3\lib\site-packages (from pykrx) (1.20.1)
Requirement already satisfied: pandas in c:\users\hingu\anaconda3\lib\site-packages (from pykrx) (1.2.4)
Requirement already satisfied: xlrd in c:\users\hingu\anaconda3\lib\site-packages (from pykrx) (2.0.1)
Requirement already satisfied: requests in c:\users\hingu\anaconda3\lib\site-packages (from pykrx) (2.25.1)
Collecting deprecated
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: zope.interface in c:\users\hingu\anaconda3\lib\site-packages (from datetime->pykrx) (5.3.0)
Requirement already satisfied: pytz in c:\users\hingu\anaconda3\lib\site-packages (from datetime->pykrx) (2021.1)
Requirement already satisfied: wrapt<2,>=1.10 in c:\users\hingu\anaconda3\lib\site-packages (from deprecated->pykrx) (1.12.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\hingu\anaconda3\lib\site-packages (from pandas->pykrx) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\users\hingu\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas->pykrx) (1.15.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\hingu\anaconda3\lib\site-packages (from requests->pykrx) (1.26.4)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\hingu\anaconda3\lib\site-packages (from requests->pykrx) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in c:\users\hingu\anaconda3\lib\site-packages (from requests->pykrx) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hingu\anaconda3\lib\site-packages (from requests->pykrx) (2020.12.5)
Requirement already satisfied: setuptools in c:\users\hingu\anaconda3\lib\site-packages (from zope.interface->datetime->pykrx) (52.0.0.post20210125)
Installing collected packages: deprecated, pykrx
Successfully installed deprecated-1.2.13 pykrx-1.0.22
Note: you may need to restart the kernel to use updated packages.

In [2]:
from pykrx import stock

### 2020.01.20 - 2021.08.31 기간 kospi 투자자별 거래량

In [23]:
investors_all = stock.get_market_trading_value_by_date("20200120", "20210831", "KOSPI")
investors_all

                    기관합계          기타법인            개인          외국인합계  전체
날짜
2020-01-20  -27825198443   19026812177  -54680450089    63478836355   0
2020-01-21 -185315141286   29582482280  360516680460  -204784021454   0
2020-01-22  288502898518    3174452321 -218208500336   -73468850503   0
2020-01-23 -479548069609   31587882970  581324527923  -133364341284   0
2020-01-28 -189417830401   47013888043  667155598342  -524751655984   0
...                  ...           ...           ...            ...  ..
2021-08-25  344961569123 -481655621271  -26684623729   163378675877   0
2021-08-26  -81422137246    4563802495  440049831171  -363191496420   0
2021-08-27  732056679957  -17256407533 -343973114787  -370827157637   0
2021-08-30  252642234837   41698411535  -57698476549  -236642169823   0
2021-08-31 -134652865595    5161108167 -993841801343  1123333558771   0

[402 rows x 5 columns]

### 2020.01.20 - 2021.08.31 기간 kospi 투자자별 매도량

In [24]:
investors_sell = stock.get_market_trading_value_by_date("20200120", "20210831", "KOSPI", on='매도')
investors_sell

,기관합계,기타법인,개인,외국인합계,전체
날짜,,,,,
2020-01-20,1490392954355,48669397945,3064999974747,1346340706153,5950403033200
2020-01-21,1290461632032,25812967584,2813413417963,1439862547343,5569550564922
2020-01-22,1273726685665,42040896183,3380963889530,1668885809925,6365617281303
2020-01-23,1904165474571,33238442629,3125771025242,1726929024705,6790103967147
2020-01-28,2183125422480,55753389826,4072431132536,2506922445998,8818232390840
...,...,...,...,...,...
2021-08-25,2397613303659,567020580485,7869813950114,2531147822385,13365595656643
2021-08-26,2462204927916,92648661634,7998635279120,2781798991679,13335287860349
2021-08-27,1801217525178,91423295918,6652955044552,2494338555432,11039934421080
2021-08-30,1755153535773,70191389075,7589645284863,2343720169598,11758710379309
2021-08-31,2520115505178,99967404185,8204341149418,5039206281114,15863630339895

### 2020.01.20 - 2021.08.31 기간 kospi 투자자별 매도량

In [25]:
investor_get = stock.get_market_trading_value_by_date("20200120", "20210831", "KOSPI", on='매수')
investor_get

,기관합계,기타법인,개인,외국인합계,전체
날짜,,,,,
2020-01-20,1462567755912,67696210122,3010319524658,1409819542508,5950403033200
2020-01-21,1105146490746,55395449864,3173930098423,1235078525889,5569550564922
2020-01-22,1562229584183,45215348504,3162755389194,1595416959422,6365617281303
2020-01-23,1424617404962,64826325599,3707095553165,1593564683421,6790103967147
2020-01-28,1993707592079,102767277869,4739586730878,1982170790014,8818232390840
...,...,...,...,...,...
2021-08-25,2742574872782,85364959214,7843129326385,2694526498262,13365595656643
2021-08-26,2380782790670,97212464129,8438685110291,2418607495259,13335287860349
2021-08-27,2533274205135,74166888385,6308981929765,2123511397795,11039934421080
2021-08-30,2007795770610,111889800610,7531946808314,2107077999775,11758710379309
2021-08-31,2385462639583,105128512352,7210499348075,6162539839885,15863630339895

### columns 확인 - 날짜 column 없음

In [30]:
investors_all.columns

Index(['기관합계', '기타법인', '개인', '외국인합계', '전체'], dtype='object')

### 날짜를 column 으로 변환

In [33]:
investors_all.reset_index(inplace = True) 
investors_all

,level_0,index,날짜,기관합계,기타법인,개인,외국인합계,전체
0,0,0,2020-01-20,-27825198443,19026812177,-54680450089,63478836355,0
1,1,1,2020-01-21,-185315141286,29582482280,360516680460,-204784021454,0
2,2,2,2020-01-22,288502898518,3174452321,-218208500336,-73468850503,0
3,3,3,2020-01-23,-479548069609,31587882970,581324527923,-133364341284,0
4,4,4,2020-01-28,-189417830401,47013888043,667155598342,-524751655984,0
...,...,...,...,...,...,...,...,...
397,397,397,2021-08-25,344961569123,-481655621271,-26684623729,163378675877,0
398,398,398,2021-08-26,-81422137246,4563802495,440049831171,-363191496420,0
399,399,399,2021-08-27,732056679957,-17256407533,-343973114787,-370827157637,0
400,400,400,2021-08-30,252642234837,41698411535,-57698476549,-236642169823,0
401,401,401,2021-08-31,-134652865595,5161108167,-993841801343,1123333558771,0

### 날짜 column 추가 확인

In [34]:
investors_all.columns

Index(['level_0', 'index', '날짜', '기관합계', '기타법인', '개인', '외국인합계', '전체'], dtype='object')

### 필요없는 column 삭제

In [ ]:
investors_all.drop('level_0',)

### csv, excel 파일로 저장

In [26]:
investors_all.to_csv("kospi_investors_all.csv", index=False)
investors_all.to_excel("kospi_investors_all.xlsx", index=False)

In [27]:
investors_sell.to_csv("kospi_investors_sell.csv", index=False)
investors_sell.to_excel("kospi_investors_sell.xlsx", index=False)

In [28]:
investor_get.to_csv("kospi_investors_get.csv", index=False)
investor_get.to_excel("kospi_investors_get.xlsx", index=False)